INSERT INTO questions (category, topic, question, option1, option2, option3, option4, answer) VALUES
-- Technical
('Technical', 'C Programming', 'Which data type is used to store decimal numbers in C?', 'int', 'float', 'char', 'void', 'float'),
('Technical', 'C Programming', 'What is the output of printf("%d", 5/2) in C?', '2', '2.5', '3', 'Error', '2'),
('Technical', 'C Programming', 'Which symbol is used for single line comment in C?', '//', '/*', '#', '--', '//'),
('Technical', 'C Programming', 'What does malloc() function do?', 'Frees memory', 'Allocates memory', 'Copies memory', 'Compares memory', 'Allocates memory'),
('Technical', 'C Programming', 'Size of int data type is typically:', '1 byte', '2 bytes', '4 bytes', '8 bytes', '4 bytes'),
('Technical', 'C Programming', 'What is the range of char data type in C?', '-128 to 127', '0 to 255', '-256 to 255', '0 to 127', '-128 to 127'),
('Technical', 'C Programming', 'Which header file is required for printf()?', 'stdlib.h', 'stdio.h', 'string.h', 'math.h', 'stdio.h'),
('Technical', 'C Programming', 'What is the correct syntax for main function?', 'void main()', 'int main()', 'main()', 'function main()', 'int main()'),
('Technical', 'C Programming', 'Which operator is used to access value at address?', '&', '*', '->', '.', '*'),
('Technical', 'C Programming', 'What does NULL pointer point to?', 'First memory location', 'Last memory location', 'No memory location', 'Random location', 'No memory location'),
('Technical', 'C++ Programming', 'Which is not a feature of OOP?', 'Encapsulation', 'Inheritance', 'Compilation', 'Polymorphism', 'Compilation'),
('Technical', 'C++ Programming', 'Which keyword is used to define class in C++?', 'class', 'struct', 'define', 'object', 'class'),
('Technical', 'C++ Programming', 'What is default access specifier for class members?', 'public', 'private', 'protected', 'friend', 'private'),
('Technical', 'C++ Programming', 'Which operator cannot be overloaded?', '+', '-', '::', '==', '::'),
('Technical', 'C++ Programming', 'What is destructor?', 'Creates object', 'Destroys object', 'Copies object', 'Compares object', 'Destroys object'),
('Technical', 'C++ Programming', 'Which is correct syntax for constructor?', 'ClassName()', '~ClassName()', 'void ClassName()', 'class ClassName()', 'ClassName()'),
('Technical', 'C++ Programming', 'What is virtual function?', 'Runtime polymorphism', 'Compile time polymorphism', 'Function overloading', 'Operator overloading', 'Runtime polymorphism'),
('Technical', 'C++ Programming', 'Which header file for cin and cout?', 'stdio.h', 'iostream', 'conio.h', 'stdlib.h', 'iostream'),
('Technical', 'C++ Programming', 'What is friend function?', 'Member of class', 'Not member but can access private', 'Static function', 'Virtual function', 'Not member but can access private'),
('Technical', 'C++ Programming', 'Which is correct for inheritance syntax?', 'class B : A', 'class B extends A', 'class B inherits A', 'class B(A)', 'class B : A'),
('Technical', 'Java Programming', 'Which keyword is used to inherit a class in Java?', 'extends', 'implements', 'inherits', 'super', 'extends'),
('Technical', 'Java Programming', 'Java is a _____ language', 'Procedural', 'Object-Oriented', 'Functional', 'Scripting', 'Object-Oriented'),
('Technical', 'Java Programming', 'Which of these is not a Java feature?', 'Platform Independent', 'Object-Oriented', 'Use of pointers', 'Multithreaded', 'Use of pointers'),
('Technical', 'Java Programming', 'Default value of boolean variable in Java is:', 'true', 'false', '0', 'null', 'false'),
('Technical', 'Java Programming', 'Which package is automatically imported in Java?', 'java.util', 'java.lang', 'java.io', 'java.net', 'java.lang'),
('Technical', 'Java Programming', 'Which method is called when an object is created?', 'main()', 'constructor', 'finalize()', 'static', 'constructor'),
('Technical', 'Java Programming', 'What is the extension of Java source code file?', '.class', '.java', '.jar', '.exe', '.java'),
('Technical', 'Java Programming', 'Which keyword is used to prevent method overriding?', 'static', 'final', 'abstract', 'private', 'final'),
('Technical', 'Java Programming', 'What is the size of int in Java?', '2 bytes', '4 bytes', '8 bytes', 'Platform dependent', '4 bytes'),
('Technical', 'Java Programming', 'Which exception is thrown when array index is out of bounds?', 'NullPointerException', 'ArrayIndexOutOfBoundsException', 'NumberFormatException', 'ArithmeticException', 'ArrayIndexOutOfBoundsException'),
('Technical', 'Python Programming', 'Which keyword is used to define a function in Python?', 'function', 'def', 'fun', 'define', 'def'),
('Technical', 'Python Programming', 'What is the output of print(2 ** 3)?', '5', '6', '8', '9', '8'),
('Technical', 'Python Programming', 'Which data structure is mutable in Python?', 'Tuple', 'String', 'List', 'Integer', 'List'),
('Technical', 'Python Programming', 'How do you start a comment in Python?', '//', '/*', '#', '--', '#'),
('Technical', 'Python Programming', 'Which function is used to get length of list?', 'length()', 'len()', 'size()', 'count()', 'len()'),
('Technical', 'Python Programming', 'What is the correct file extension for Python files?', '.pt', '.python', '.py', '.p', '.py'),
('Technical', 'Python Programming', 'Which keyword is used for loop in Python?', 'loop', 'foreach', 'for', 'repeat', 'for'),
('Technical', 'Python Programming', 'What does // operator do in Python?', 'Division', 'Floor Division', 'Modulo', 'Exponent', 'Floor Division'),
('Technical', 'Python Programming', 'Which method is used to add element at end of list?', 'add()', 'append()', 'insert()', 'push()', 'append()'),
('Technical', 'Python Programming', 'What is the output of print(type([]))?', '<class list>', '<class dict>', '<class tuple>', '<class set>', '<class list>'),
('Technical', 'JavaScript', 'Which company developed JavaScript?', 'Microsoft', 'Netscape', 'Oracle', 'IBM', 'Netscape'),
('Technical', 'JavaScript', 'Which symbol is used for comments in JavaScript?', '//', '#', '/*', '--', '//'),
('Technical', 'JavaScript', 'Which method is used to parse a string to integer?', 'parseInt()', 'parseFloat()', 'toInt()', 'Number()', 'parseInt()'),
('Technical', 'JavaScript', 'What is the correct syntax for referring to external script?', '<script href="xxx.js">', '<script name="xxx.js">', '<script src="xxx.js">', '<script file="xxx.js">', '<script src="xxx.js">'),
('Technical', 'JavaScript', 'How do you create a function in JavaScript?', 'function myFunction()', 'function:myFunction()', 'function = myFunction()', 'def myFunction()', 'function myFunction()'),
('Technical', 'JavaScript', 'How do you write "Hello World" in an alert box?', 'alertBox("Hello World")', 'msgBox("Hello World")', 'alert("Hello World")', 'msg("Hello World")', 'alert("Hello World")'),
('Technical', 'JavaScript', 'Which operator is used to assign a value to a variable?', '×', '*', '=', '-', '='),
('Technical', 'JavaScript', 'What will typeof null return?', 'null', 'undefined', 'object', 'number', 'object'),
('Technical', 'JavaScript', 'Which method is used to convert JSON string to JavaScript object?', 'JSON.parse()', 'JSON.stringify()', 'JSON.toObject()', 'JSON.convert()', 'JSON.parse()'),
('Technical', 'JavaScript', 'What is the correct way to write an array in JavaScript?', 'var colors = "red", "green", "blue"', 'var colors = ["red", "green", "blue"]', 'var colors = (1:"red", 2:"green", 3:"blue")', 'var colors = 1 = ("red"), 2 = ("green")', 'var colors = ["red", "green", "blue"]'),
('Technical', 'HTML', 'What does HTML stand for?', 'Hyper Text Markup Language', 'High Text Markup Language', 'Hyper Tabular Markup Language', 'None of these', 'Hyper Text Markup Language'),
('Technical', 'HTML', 'Which HTML tag is used to define an internal style sheet?', '<css>', '<script>', '<style>', '<link>', '<style>'),
('Technical', 'HTML', 'Which tag is used for creating a hyperlink?', '<link>', '<a>', '<href>', '<hyperlink>', '<a>'),
('Technical', 'HTML', 'Which attribute is used to provide a unique name to an element?', 'class', 'id', 'name', 'title', 'id'),
('Technical', 'HTML', 'Which tag is used to insert an image?', '<image>', '<img>', '<picture>', '<src>', '<img>'),
('Technical', 'HTML', 'What is the correct HTML for creating a checkbox?', '<checkbox>', '<input type="check">', '<input type="checkbox">', '<check>', '<input type="checkbox">'),
('Technical', 'HTML', 'Which tag is used to define an unordered list?', '<ol>', '<ul>', '<list>', '<dl>', '<ul>'),
('Technical', 'HTML', 'Which attribute specifies an alternate text for an image?', 'title', 'alt', 'src', 'longdesc', 'alt'),
('Technical', 'HTML', 'Which tag is used to create a table?', '<tab>', '<table>', '<tr>', '<td>', '<table>'),
('Technical', 'HTML', 'What is the correct HTML for making a text bold?', '<bold>', '<b>', '<strong>', 'Both <b> and <strong>', 'Both <b> and <strong>'),
('Technical', 'CSS', 'What does CSS stand for?', 'Cascading Style Sheets', 'Creative Style Sheets', 'Computer Style Sheets', 'Colorful Style Sheets', 'Cascading Style Sheets'),
('Technical', 'CSS', 'Which property is used to change the background color?', 'bgcolor', 'color', 'background-color', 'bg-color', 'background-color'),
('Technical', 'CSS', 'Which property is used to change the font of an element?', 'font-family', 'font-style', 'font-weight', 'text-font', 'font-family'),
('Technical', 'CSS', 'How do you select an element with id "demo"?', '.demo', '#demo', 'demo', '*demo', '#demo'),
('Technical', 'CSS', 'How do you select elements with class name "test"?', '#test', '.test', 'test', '*test', '.test'),
('Technical', 'CSS', 'Which property is used to change the text color?', 'text-color', 'fgcolor', 'color', 'font-color', 'color'),
('Technical', 'CSS', 'How do you add a background color for all <h1> elements?', 'h1 {background-color:#FFFFFF}', 'h1.all {background-color:#FFFFFF}', 'all.h1 {background-color:#FFFFFF}', 'h1:all {background-color:#FFFFFF}', 'h1 {background-color:#FFFFFF}'),
('Technical', 'CSS', 'Which property is used to change the left margin of an element?', 'margin-left', 'padding-left', 'indent', 'text-indent', 'margin-left'),
('Technical', 'CSS', 'How do you make text bold in CSS?', 'font-weight:bold', 'font:bold', 'style:bold', 'text:bold', 'font-weight:bold'),
('Technical', 'CSS', 'Which property is used to change the size of text?', 'text-size', 'font-size', 'text-style', 'font-style', 'font-size'),
('Technical', 'SQL/DBMS', 'SQL stands for:', 'Structured Query Language', 'Simple Query Language', 'Standard Query Language', 'System Query Language', 'Structured Query Language'),
('Technical', 'SQL/DBMS', 'Which command is used to retrieve data from database?', 'GET', 'SELECT', 'RETRIEVE', 'FETCH', 'SELECT'),
('Technical', 'SQL/DBMS', 'Primary key can contain:', 'Duplicate values', 'NULL values', 'Unique values only', 'Any values', 'Unique values only'),
('Technical', 'SQL/DBMS', 'Which clause is used to filter records in SQL?', 'FILTER', 'WHERE', 'HAVING', 'IF', 'WHERE'),
('Technical', 'SQL/DBMS', 'What does DDL stand for?', 'Data Definition Language', 'Data Delete Language', 'Data Duplicate Language', 'Database Definition Language', 'Data Definition Language'),
('Technical', 'SQL/DBMS', 'Which command is used to delete all records from table?', 'DELETE', 'TRUNCATE', 'DROP', 'REMOVE', 'TRUNCATE'),
('Technical', 'SQL/DBMS', 'Which key uniquely identifies a record in another table?', 'Primary Key', 'Foreign Key', 'Candidate Key', 'Super Key', 'Foreign Key'),
('Technical', 'SQL/DBMS', 'What is normalization?', 'Data backup', 'Removing redundancy', 'Creating indexes', 'Data encryption', 'Removing redundancy'),
('Technical', 'SQL/DBMS', 'Which command is used to add new column to table?', 'ADD COLUMN', 'ALTER TABLE', 'MODIFY TABLE', 'UPDATE TABLE', 'ALTER TABLE'),
('Technical', 'SQL/DBMS', 'ACID properties are related to:', 'Database Security', 'Transactions', 'Normalization', 'Indexing', 'Transactions'),
('Technical', 'Data Structures', 'LIFO principle is used in:', 'Queue', 'Stack', 'Tree', 'Graph', 'Stack'),
('Technical', 'Data Structures', 'FIFO principle is used in:', 'Queue', 'Stack', 'Tree', 'Linked List', 'Queue'),
('Technical', 'Data Structures', 'Time complexity of binary search is:', 'O(n)', 'O(log n)', 'O(n^2)', 'O(1)', 'O(log n)'),
('Technical', 'Data Structures', 'Which data structure uses nodes and pointers?', 'Array', 'Linked List', 'Stack', 'Queue', 'Linked List'),
('Technical', 'Data Structures', 'What is the worst case time complexity of Quick Sort?', 'O(n log n)', 'O(n^2)', 'O(n)', 'O(log n)', 'O(n^2)'),
('Technical', 'Data Structures', 'Which traversal visits root node first?', 'Inorder', 'Preorder', 'Postorder', 'Level order', 'Preorder'),
('Technical', 'Data Structures', 'What is the space complexity of recursive function with depth n?', 'O(1)', 'O(n)', 'O(log n)', 'O(n^2)', 'O(n)'),
('Technical', 'Data Structures', 'Hash table uses which technique to handle collisions?', 'Sorting', 'Chaining', 'Indexing', 'Merging', 'Chaining'),
('Technical', 'Data Structures', 'Which data structure is best for implementing priority queue?', 'Array', 'Linked List', 'Heap', 'Stack', 'Heap'),
('Technical', 'Data Structures', 'What is the time complexity to access element in array by index?', 'O(1)', 'O(n)', 'O(log n)', 'O(n^2)', 'O(1)'),
('Technical', 'Operating System', 'Which scheduling algorithm can cause starvation?', 'FCFS', 'Round Robin', 'Priority', 'SJF', 'Priority'),
('Technical', 'Operating System', 'Full form of OS is:', 'Open Source', 'Operating System', 'Optical System', 'Online System', 'Operating System'),
('Technical', 'Operating System', 'A process that is waiting for CPU is in which state?', 'Running', 'Ready', 'Blocked', 'Terminated', 'Ready'),
('Technical', 'Operating System', 'Which memory management technique divides memory into fixed-size blocks?', 'Paging', 'Segmentation', 'Swapping', 'Partitioning', 'Paging'),
('Technical', 'Operating System', 'What is thrashing in OS?', 'CPU utilization', 'Excessive paging', 'Memory leak', 'Disk formatting', 'Excessive paging'),
('Technical', 'Operating System', 'Deadlock occurs when:', 'Process completes', 'Circular wait exists', 'CPU is idle', 'Memory is full', 'Circular wait exists'),
('Technical', 'Operating System', 'Which algorithm is used for page replacement?', 'FCFS', 'LRU', 'Priority', 'Round Robin', 'LRU'),
('Technical', 'Operating System', 'What is the purpose of semaphore?', 'Memory allocation', 'Process synchronization', 'File management', 'CPU scheduling', 'Process synchronization'),
('Technical', 'Operating System', 'Critical section problem is related to:', 'Deadlock', 'Synchronization', 'Scheduling', 'Memory', 'Synchronization'),
('Technical', 'Operating System', 'Which is not a type of operating system?', 'Batch', 'Real-time', 'Distributed', 'Compiled', 'Compiled'),
('Technical', 'Computer Networks', 'What does IP stand for?', 'Internet Protocol', 'Internal Protocol', 'Internet Process', 'Internal Process', 'Internet Protocol'),
('Technical', 'Computer Networks', 'Which layer is responsible for routing in OSI model?', 'Physical', 'Data Link', 'Network', 'Transport', 'Network'),
('Technical', 'Computer Networks', 'What is the size of IPv4 address?', '16 bits', '32 bits', '64 bits', '128 bits', '32 bits'),
('Technical', 'Computer Networks', 'Which protocol is used for email?', 'HTTP', 'FTP', 'SMTP', 'TCP', 'SMTP'),
('Technical', 'Computer Networks', 'Full form of TCP:', 'Transfer Control Protocol', 'Transmission Control Protocol', 'Transfer Communication Protocol', 'Transmission Communication Protocol', 'Transmission Control Protocol'),
('Technical', 'Computer Networks', 'Which device works at Network layer?', 'Hub', 'Switch', 'Router', 'Bridge', 'Router'),
('Technical', 'Computer Networks', 'What is the default port for HTTP?', '21', '25', '80', '443', '80'),
('Technical', 'Computer Networks', 'Which topology has a central node?', 'Bus', 'Ring', 'Star', 'Mesh', 'Star'),
('Technical', 'Computer Networks', 'DNS stands for:', 'Domain Name System', 'Domain Network System', 'Digital Name System', 'Digital Network System', 'Domain Name System'),
('Technical', 'Computer Networks', 'Which protocol is connectionless?', 'TCP', 'UDP', 'HTTP', 'FTP', 'UDP'),
('Technical', 'Software Engineering', 'Which is a software development model?', 'Waterfall', 'River', 'Ocean', 'Stream', 'Waterfall'),
('Technical', 'Software Engineering', 'What does SDLC stand for?', 'Software Development Life Cycle', 'System Development Life Cycle', 'Software Design Life Cycle', 'System Design Life Cycle', 'Software Development Life Cycle'),
('Technical', 'Software Engineering', 'Which phase comes first in SDLC?', 'Design', 'Testing', 'Requirements', 'Coding', 'Requirements'),
('Technical', 'Software Engineering', 'What is white box testing?', 'Testing based on code', 'Testing without code', 'User testing', 'Performance testing', 'Testing based on code'),
('Technical', 'Software Engineering', 'Which is an agile methodology?', 'Waterfall', 'Scrum', 'Spiral', 'V-Model', 'Scrum'),
('Technical', 'Software Engineering', 'What is regression testing?', 'Testing new features', 'Re-testing after changes', 'Performance testing', 'Security testing', 'Re-testing after changes'),
('Technical', 'Software Engineering', 'Which diagram is used in UML?', 'Flow chart', 'Use case diagram', 'ER diagram', 'Decision tree', 'Use case diagram'),
('Technical', 'Software Engineering', 'What is the main purpose of testing?', 'Find defects', 'Write code', 'Design system', 'Deploy software', 'Find defects'),
('Technical', 'Software Engineering', 'Which is a version control system?', 'Git', 'Java', 'Python', 'MySQL', 'Git'),
('Technical', 'Software Engineering', 'What is SRS document?', 'Software Requirements Specification', 'System Requirements Specification', 'Software Research Specification', 'System Research Specification', 'Software Requirements Specification'),
('Technical', 'Cloud Computing', 'Which is a cloud service model?', 'SaaS', 'DaaS', 'NaaS', 'All of these', 'All of these'),
('Technical', 'Cloud Computing', 'What does IaaS stand for?', 'Internet as a Service', 'Infrastructure as a Service', 'Information as a Service', 'Integration as a Service', 'Infrastructure as a Service'),
('Technical', 'Cloud Computing', 'Which company provides AWS?', 'Google', 'Microsoft', 'Amazon', 'IBM', 'Amazon'),
('Technical', 'Cloud Computing', 'What is PaaS?', 'Platform as a Service', 'Product as a Service', 'Process as a Service', 'Protocol as a Service', 'Platform as a Service'),
('Technical', 'Cloud Computing', 'Which is a public cloud provider?', 'AWS', 'Private cloud', 'Hybrid cloud', 'Community cloud', 'AWS'),
('Technical', 'Cloud Computing', 'What is virtualization?', 'Creating virtual resources', 'Creating physical resources', 'Deleting resources', 'None of these', 'Creating virtual resources'),
('Technical', 'Cloud Computing', 'Which service is provided by Azure?', 'Virtual Machines', 'Physical Machines', 'Hardware', 'None of these', 'Virtual Machines'),
('Technical', 'Cloud Computing', 'What is scalability in cloud?', 'Ability to scale resources', 'Fixed resources', 'Limited resources', 'None of these', 'Ability to scale resources'),
('Technical', 'Cloud Computing', 'Which is a cloud deployment model?', 'Public', 'Private', 'Hybrid', 'All of these', 'All of these'),
('Technical', 'Cloud Computing', 'What is cloud storage?', 'Storing data on cloud', 'Storing data locally', 'Deleting data', 'None of these', 'Storing data on cloud'),,
