INSERT INTO questions (category, topic, question, option1, option2, option3, option4, answer) VALUES
-- Reasoning
('Reasoning', 'Logical Reasoning', 'All cats are animals. Some animals are dogs. Therefore:', 'All dogs are cats', 'Some cats are dogs', 'All animals are cats', 'None can be concluded', 'None can be concluded'),
('Reasoning', 'Logical Reasoning', 'Find the odd one out: 2, 4, 6, 9, 10', '2', '4', '9', '10', '9'),
('Reasoning', 'Logical Reasoning', 'If COMPUTER is coded as DPNQVUFS, how is MOUSE coded?', 'NPVTF', 'NQVTF', 'LPSTF', 'MQVTF', 'NPVTF'),
('Reasoning', 'Logical Reasoning', 'Complete the series: 2, 6, 12, 20, 30, ?', '40', '42', '44', '46', '42'),
('Reasoning', 'Logical Reasoning', 'If + means ×, × means -, - means ÷, and ÷ means +, then 8 + 2 - 4 ÷ 3 = ?', '5', '7', '9', '11', '7'),
('Reasoning', 'Logical Reasoning', 'Find next in series: AB, DEF, GHIJ, ?', 'KLMNO', 'KLMN', 'LMNOP', 'MNOP', 'KLMNO'),
('Reasoning', 'Logical Reasoning', 'If FRIEND is coded as HUMJTK, how is CANDLE coded?', 'EDRIRL', 'ECPNMF', 'DEQHOB', 'DBOCMF', 'DEQHOB'),
('Reasoning', 'Logical Reasoning', 'Pointing to a man, a woman said, "His mother is the only daughter of my mother." How is the woman related to man?', 'Mother', 'Daughter', 'Sister', 'Aunt', 'Mother'),
('Reasoning', 'Logical Reasoning', 'In a certain code, RAIN is written as 8$%6 and MORE is written as 7#8@. How is REMAIN written?', '8@7$%6', '8$7%@6', '8@%7$6', '8$%@76', '8@7$%6'),
('Reasoning', 'Logical Reasoning', 'If 5th day after tomorrow is Friday, what day was 3 days before yesterday?', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Thursday'),
('Reasoning', 'Verbal Reasoning', 'Choose the synonym of ABUNDANT:', 'Scarce', 'Plentiful', 'Limited', 'Rare', 'Plentiful'),
('Reasoning', 'Verbal Reasoning', 'Choose the antonym of OPTIMISTIC:', 'Hopeful', 'Positive', 'Pessimistic', 'Cheerful', 'Pessimistic'),
('Reasoning', 'Verbal Reasoning', 'Complete: Book is to Reading as Fork is to?', 'Drawing', 'Writing', 'Eating', 'Stirring', 'Eating'),
('Reasoning', 'Verbal Reasoning', 'Choose synonym of CANDID:', 'Frank', 'Secretive', 'Dishonest', 'Clever', 'Frank'),
('Reasoning', 'Verbal Reasoning', 'Choose antonym of ARTIFICIAL:', 'Fake', 'Natural', 'Synthetic', 'Man-made', 'Natural'),
('Reasoning', 'Verbal Reasoning', 'Complete: Dog is to Bark as Cat is to?', 'Meow', 'Howl', 'Roar', 'Chirp', 'Meow'),
('Reasoning', 'Verbal Reasoning', 'Choose synonym of ENORMOUS:', 'Tiny', 'Huge', 'Small', 'Medium', 'Huge'),
('Reasoning', 'Verbal Reasoning', 'Choose antonym of COURAGE:', 'Bravery', 'Fear', 'Valor', 'Boldness', 'Fear'),
('Reasoning', 'Verbal Reasoning', 'Complete: Pen is to Write as Knife is to?', 'Read', 'Cut', 'Eat', 'Cook', 'Cut'),
('Reasoning', 'Verbal Reasoning', 'Choose synonym of BRIEF:', 'Long', 'Short', 'Detailed', 'Extended', 'Short'),
('Reasoning', 'Analytical Reasoning', 'If A is taller than B, and B is taller than C, then:', 'C is tallest', 'A is tallest', 'B is tallest', 'Cannot determine', 'A is tallest'),
('Reasoning', 'Analytical Reasoning', 'In a row of 40 students, Sam is 16th from left. What is his position from right?', '24', '25', '26', '27', '25'),
('Reasoning', 'Analytical Reasoning', 'A is B\'s brother. B is C\'s mother. D is C\'s father. How is A related to D?', 'Brother', 'Brother-in-law', 'Son', 'Cousin', 'Brother-in-law'),
('Reasoning', 'Analytical Reasoning', 'If South-East becomes North, what will West become?', 'North-East', 'South-East', 'North-West', 'South-West', 'South-East'),
('Reasoning', 'Analytical Reasoning', 'A clock shows 3:00. What is the angle between hour and minute hands?', '60°', '75°', '90°', '120°', '90°'),
('Reasoning', 'Analytical Reasoning', 'Five friends are sitting in a row. A is to the left of B but right of C. D is right of B. E is right of D. Who is in the middle?', 'A', 'B', 'C', 'D', 'B'),
('Reasoning', 'Analytical Reasoning', 'If 1st January 2024 is Monday, what day is 1st January 2025?', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Wednesday'),
('Reasoning', 'Analytical Reasoning', 'In a family of 6, M is son of Q, but Q is not mother of M. P is daughter of Q. R is brother of P. How is Q related to R?', 'Mother', 'Father', 'Aunt', 'Uncle', 'Father'),
('Reasoning', 'Analytical Reasoning', 'If P $ Q means P is father of Q, P # Q means P is mother of Q, P * Q means P is sister of Q. What does A $ B # C * D mean?', 'A is grandfather of D', 'A is father of D', 'A is uncle of D', 'A is brother of D', 'A is grandfather of D'),
('Reasoning', 'Analytical Reasoning', 'In a class, Ram ranks 7th from top and 26th from bottom. How many students are in the class?', '31', '32', '33', '34', '32'),
('Reasoning', 'Number Series', 'Find next: 2, 4, 8, 16, ?', '24', '28', '32', '36', '32'),
('Reasoning', 'Number Series', 'Find next: 1, 4, 9, 16, 25, ?', '30', '32', '34', '36', '36'),
('Reasoning', 'Number Series', 'Find next: 3, 6, 12, 24, ?', '36', '40', '48', '52', '48'),
('Reasoning', 'Number Series', 'Find next: 5, 10, 20, 40, ?', '60', '70', '80', '90', '80'),
('Reasoning', 'Number Series', 'Find next: 1, 1, 2, 3, 5, 8, ?', '11', '12', '13', '14', '13'),
('Reasoning', 'Number Series', 'Find next: 2, 5, 10, 17, 26, ?', '35', '36', '37', '38', '37'),
('Reasoning', 'Number Series', 'Find next: 7, 14, 28, 56, ?', '84', '98', '102', '112', '112'),
('Reasoning', 'Number Series', 'Find next: 3, 9, 27, 81, ?', '162', '216', '243', '324', '243'),
('Reasoning', 'Number Series', 'Find next: 11, 13, 17, 19, 23, ?', '27', '29', '31', '33', '29'),
('Reasoning', 'Number Series', 'Find next: 100, 50, 25, 12.5, ?', '5', '6.25', '7.5', '10', '6.25'),
('Reasoning', 'Letter Series', 'Find next: A, C, E, G, ?', 'H', 'I', 'J', 'K', 'I'),
('Reasoning', 'Letter Series', 'Find next: B, D, F, H, ?', 'I', 'J', 'K', 'L', 'J'),
('Reasoning', 'Letter Series', 'Find next: Z, X, V, T, ?', 'P', 'Q', 'R', 'S', 'R'),
('Reasoning', 'Letter Series', 'Find next: ACE, FHJ, KMO, ?', 'NPR', 'PRT', 'PRV', 'QSU', 'PRT'),
('Reasoning', 'Letter Series', 'Find next: BAC, DFE, HJG, ?', 'LMI', 'LNI', 'MNI', 'LNJ', 'LNI'),
('Reasoning', 'Letter Series', 'Find next: AZ, BY, CX, ?', 'DV', 'DW', 'EW', 'EV', 'DW'),
('Reasoning', 'Letter Series', 'Find next: AB, CD, EF, GH, ?', 'HI', 'IJ', 'JK', 'KL', 'IJ'),
('Reasoning', 'Letter Series', 'Find next: PQR, STU, VWX, ?', 'XYZ', 'YZA', 'ZAB', 'ABC', 'YZA'),
('Reasoning', 'Letter Series', 'Find next: ACF, BEG, CFH, ?', 'DGI', 'DEI', 'DFI', 'EGI', 'DGI'),
('Reasoning', 'Letter Series', 'Find next: MN, OP, QR, ?', 'RS', 'ST', 'TU', 'UV', 'ST'),
('Reasoning', 'Blood Relations', 'Pointing to a photograph, a man says, "She is the daughter of my grandfather\'s only son." Who is in the photograph?', 'His daughter', 'His sister', 'His niece', 'His mother', 'His daughter'),
('Reasoning', 'Blood Relations', 'A is B\'s sister. C is B\'s mother. D is C\'s father. How is A related to D?', 'Grandmother', 'Granddaughter', 'Daughter', 'Cannot determine', 'Granddaughter'),
('Reasoning', 'Blood Relations', 'If A + B means A is brother of B, A × B means A is son of B, A ÷ B means A is wife of B. What does P + Q × R ÷ S mean?', 'P is uncle of S', 'P is nephew of S', 'P is brother of S', 'P is son of S', 'P is uncle of S'),
('Reasoning', 'Blood Relations', 'Introducing a man, a woman says, "He is the only son of my mother\'s mother." How is the man related to woman?', 'Uncle', 'Father', 'Brother', 'Cousin', 'Uncle'),
('Reasoning', 'Blood Relations', 'A is father of C and D is son of B. E is brother of A. If C is sister of D, how is B related to E?', 'Sister', 'Sister-in-law', 'Brother', 'Brother-in-law', 'Sister-in-law'),
('Reasoning', 'Blood Relations', 'P is Q\'s brother. R is Q\'s mother. S is R\'s father. T is S\'s mother. How is P related to T?', 'Grandson', 'Granddaughter', 'Great grandson', 'Great granddaughter', 'Great grandson'),
('Reasoning', 'Blood Relations', 'Pointing to a boy, Meena says, "He is the son of my grandfather\'s only daughter." How is boy related to Meena?', 'Brother', 'Son', 'Uncle', 'Cousin', 'Brother'),
('Reasoning', 'Blood Relations', 'A is B\'s brother. C is D\'s father. E is B\'s mother. A and D are brothers. How is E related to C?', 'Sister', 'Sister-in-law', 'Mother', 'Wife', 'Wife'),
('Reasoning', 'Blood Relations', 'M is son of P. Q is daughter of M. S is aunt of Q. R is daughter of S. How is M related to R?', 'Uncle', 'Cousin', 'Brother', 'Father', 'Uncle'),
('Reasoning', 'Blood Relations', 'A and B are brothers. C and D are sisters. A\'s son is D\'s brother. How is B related to C?', 'Father', 'Brother', 'Uncle', 'Grandfather', 'Uncle'),
('Reasoning', 'Coding-Decoding', 'If CAT is coded as 24120, how is DOG coded?', '4157', '41520', '4715', '31512', '4157'),
('Reasoning', 'Coding-Decoding', 'If DELHI is coded as CCIDD, how is BOMBAY coded?', 'ALCXV', 'ANLXZ', 'BNCXZ', 'ANLYY', 'ANLXZ'),
('Reasoning', 'Coding-Decoding', 'In a code, ROAD is URDG. How is SWAN coded?', 'VZDQ', 'VYCQ', 'UYBP', 'VZCP', 'VZDQ'),
('Reasoning', 'Coding-Decoding', 'If CLOCK is coded as KCOLC, how is TABLE coded?', 'ELBAT', 'BELAT', 'ELBAL', 'BLATE', 'ELBAT'),
('Reasoning', 'Coding-Decoding', 'If MISTAKE is coded as 9765412, how is TAKE coded?', '1152', '1412', '5412', '4152', '5412'),
('Reasoning', 'Coding-Decoding', 'In a code, MONKEY is XDJMNL. How is TIGER coded?', 'SHFDQ', 'UJHFS', 'QDFHS', 'SDFHT', 'SHFDQ'),
('Reasoning', 'Coding-Decoding', 'If ROSE is coded as TQUG, how is CHAIR coded?', 'EJCKT', 'EJCKR', 'DKBHS', 'EJCHQ', 'EJCKT'),
('Reasoning', 'Coding-Decoding', 'If EARTH is written as 41590, how is HEART written?', '04159', '81459', '81950', '04951', '81459'),
('Reasoning', 'Coding-Decoding', 'In a certain code, if LEMON is 56789 and MELON is 86579, what is MELON?', '86579', '76589', '68759', '57689', '86579'),
('Reasoning', 'Coding-Decoding', 'If SERVANT is coded as VBOERS, how is KITCHEN coded?', 'HCITEN', 'NEHCTIK', 'NEHCITK', 'ITCHEKN', 'NEHCTIK'),
('Reasoning', 'Direction Sense', 'A person walks 10m north, then 10m east, then 10m south. How far is he from starting point?', '5m', '8m', '10m', '15m', '10m'),
('Reasoning', 'Direction Sense', 'Ram walks 20m north, turns right and walks 30m, then turns right again and walks 35m. How far is he from starting point?', '25m', '30m', '35m', '40m', '25m'),
('Reasoning', 'Direction Sense', 'A man faces north. He turns 45° clockwise, then 180° anticlockwise. Which direction is he facing?', 'North-East', 'South-West', 'South-East', 'North-West', 'South-West'),
('Reasoning', 'Direction Sense', 'Starting from a point, A walks 5m south, then 3m east, then 5m north. In which direction is he from starting point?', 'East', 'West', 'North', 'South', 'East'),
('Reasoning', 'Direction Sense', 'A man is facing west. He turns 45° clockwise, then another 180° clockwise. Which direction is he facing?', 'North-East', 'South-East', 'South-West', 'North-West', 'South-East'),
('Reasoning', 'Direction Sense', 'Ravi walks 6m north, 8m east. What is minimum distance from starting point?', '8m', '10m', '12m', '14m', '10m'),
('Reasoning', 'Direction Sense', 'A boy walks 30m towards north, turns left and walks 40m, then turns left and walks 30m. How far is he from starting point?', '30m', '35m', '40m', '45m', '40m'),
('Reasoning', 'Direction Sense', 'Amit walks 4m towards east, turns right and walks 3m, then turns left and walks 5m. How far and in which direction from starting point?', '9m East', '9m North', '9m West', '9m South', '9m East'),
('Reasoning', 'Direction Sense', 'A man faces south. He turns 135° anticlockwise. Which direction is he facing?', 'North-East', 'South-East', 'North-West', 'South-West', 'North-East'),
('Reasoning', 'Direction Sense', 'Suresh walks 7m east, then 24m north. What is shortest distance from start?', '20m', '23m', '25m', '30m', '25m'),
('Reasoning', 'Ranking & Order', 'In a class of 40 students, Karan ranks 10th from top. What is his rank from bottom?', '30', '31', '32', '33', '31'),
('Reasoning', 'Ranking & Order', 'Amit ranks 16th from top and 49th from bottom in class. How many students are there?', '63', '64', '65', '66', '64'),
('Reasoning', 'Ranking & Order', 'In a row, Mohan is 12th from left and Sohan is 18th from right. If they interchange, Mohan becomes 20th from left. What is position of Sohan from right?', '18', '20', '22', '26', '26'),
('Reasoning', 'Ranking & Order', 'In a class, Ravi is 18th from top and 24th from bottom. How many students are in class?', '40', '41', '42', '43', '41'),
('Reasoning', 'Ranking & Order', 'A is taller than B but shorter than C. D is taller than A but shorter than C. Who is tallest?', 'A', 'B', 'C', 'D', 'C'),
('Reasoning', 'Ranking & Order', 'In a queue, A is 10th from front and B is 25th from back. If they interchange, A becomes 15th from front. What is total strength?', '35', '38', '39', '40', '39'),
('Reasoning', 'Ranking & Order', 'P is heavier than Q but lighter than R. S is heavier than P but lighter than R. Who is heaviest?', 'P', 'Q', 'R', 'S', 'R'),
('Reasoning', 'Ranking & Order', 'In a row of 21 girls, when Monika was shifted 4 places to right, she became 12th from left. What was her original position?', '6th', '7th', '8th', '9th', '8th'),
('Reasoning', 'Ranking & Order', 'Among 5 friends, A is taller than B but shorter than C. D is shortest. E is taller than C. Who is third tallest?', 'A', 'B', 'C', 'E', 'A'),
('Reasoning', 'Ranking & Order', 'In a row, A is 7th from left and 12th from right. How many people are in the row?', '17', '18', '19', '20', '18'),
('Reasoning', 'Syllogism', 'All birds are trees. All trees are roads. Therefore:', 'All birds are roads', 'All roads are birds', 'Some roads are birds', 'No bird is road', 'All birds are roads'),
('Reasoning', 'Syllogism', 'Some cats are dogs. All dogs are animals. Therefore:', 'All cats are animals', 'Some cats are animals', 'All animals are cats', 'Cannot determine', 'Some cats are animals'),
('Reasoning', 'Syllogism', 'All pens are books. Some books are pencils. Therefore:', 'All pens are pencils', 'Some pens are pencils', 'All pencils are books', 'Cannot determine', 'Cannot determine'),
('Reasoning', 'Syllogism', 'No student is teacher. All teachers are educated. Therefore:', 'No student is educated', 'Some students are educated', 'Cannot determine', 'All educated are teachers', 'Cannot determine'),
('Reasoning', 'Syllogism', 'All roses are flowers. All flowers are beautiful. Therefore:', 'All roses are beautiful', 'All beautiful are roses', 'Some roses are beautiful', 'Cannot determine', 'All roses are beautiful'),
('Reasoning', 'Syllogism', 'Some doctors are engineers. All engineers are smart. Therefore:', 'All doctors are smart', 'Some doctors are smart', 'All smart are doctors', 'Cannot determine', 'Some doctors are smart'),
('Reasoning', 'Syllogism', 'All apples are fruits. No fruit is vegetable. Therefore:', 'No apple is vegetable', 'All vegetables are apples', 'Some apples are vegetables', 'Cannot determine', 'No apple is vegetable'),
('Reasoning', 'Syllogism', 'Some cars are buses. All buses are vehicles. Therefore:', 'All cars are vehicles', 'Some cars are vehicles', 'All vehicles are cars', 'Cannot determine', 'Some cars are vehicles'),
('Reasoning', 'Syllogism', 'All dogs are mammals. All mammals are animals. Therefore:', 'All dogs are animals', 'All animals are dogs', 'Some animals are dogs', 'Cannot determine', 'All dogs are animals'),
('Reasoning', 'Syllogism', 'No fish is bird. All birds can fly. Therefore:', 'No fish can fly', 'All fish can fly', 'Some fish can fly', 'Cannot determine', 'Cannot determine'),
('Reasoning', 'Data Sufficiency', 'What is John\'s age? I) John is 25 years younger than his father II) John\'s sister is 5 years older than John', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Neither sufficient'),
('Reasoning', 'Data Sufficiency', 'What is area of circle? I) Radius is 7 cm II) Circumference is 44 cm', 'I alone sufficient', 'II alone sufficient', 'Either I or II', 'Both needed', 'Either I or II'),
('Reasoning', 'Data Sufficiency', 'Is X > Y? I) X + Y = 10 II) X - Y = 4', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Both needed'),
('Reasoning', 'Data Sufficiency', 'What is profit%? I) CP = Rs.100 II) SP = Rs.120', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Both needed'),
('Reasoning', 'Data Sufficiency', 'How many students passed? I) 60% students passed II) 40 students failed', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Both needed'),
('Reasoning', 'Data Sufficiency', 'What is speed of train? I) Train crosses a pole in 10 seconds II) Length of train is 100m', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Both needed'),
('Reasoning', 'Data Sufficiency', 'Is A brother of B? I) C is father of A II) C has only one son', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Neither sufficient'),
('Reasoning', 'Data Sufficiency', 'What is principal amount? I) SI = Rs.100 II) Rate = 5%, Time = 2 years', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Both needed'),
('Reasoning', 'Data Sufficiency', 'How many people are in the queue? I) Ajay is 15th from front II) Ajay is 20th from back', 'I alone sufficient', 'II alone sufficient', 'Both needed', 'Neither sufficient', 'Both needed'),
('Reasoning', 'Data Sufficiency', 'What is the code for MOTHER? I) FATHER is coded as GBUIFS II) SISTER is coded as TJTUF', 'I alone sufficient', 'II alone sufficient', 'Either I or II', 'Both needed', 'Either I or II'),
('Reasoning', 'Statement & Conclusion', 'Statement: All intelligent are hardworking. Conclusion: Some hardworking are intelligent.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Follows'),
('Reasoning', 'Statement & Conclusion', 'Statement: No animal is plant. Conclusion: All plants are animals.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Does not follow'),
('Reasoning', 'Statement & Conclusion', 'Statement: Some books are pens. Conclusion: All pens are books.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Does not follow'),
('Reasoning', 'Statement & Conclusion', 'Statement: All teachers are educated. Some educated are doctors. Conclusion: Some teachers are doctors.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Does not follow'),
('Reasoning', 'Statement & Conclusion', 'Statement: Quality of education is deteriorating. Conclusion: Educated people are decreasing.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Does not follow'),
('Reasoning', 'Statement & Conclusion', 'Statement: All roses are flowers. All flowers are beautiful. Conclusion: All roses are beautiful.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Follows'),
('Reasoning', 'Statement & Conclusion', 'Statement: Some cats are dogs. All dogs bark. Conclusion: Some cats bark.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Follows'),
('Reasoning', 'Statement & Conclusion', 'Statement: No pen is pencil. Conclusion: No pencil is pen.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Follows'),
('Reasoning', 'Statement & Conclusion', 'Statement: Reading is good habit. Conclusion: All readers are good people.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Does not follow'),
('Reasoning', 'Statement & Conclusion', 'Statement: All mangoes are fruits. Conclusion: All fruits are mangoes.', 'Follows', 'Does not follow', 'Cannot determine', 'Partially follows', 'Does not follow'),
('Reasoning', 'Statement & Assumption', 'Statement: "Use our toothpaste for healthy teeth" - Advertisement. Assumption: People want healthy teeth.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Please do not use lift while going down. Assumption: Lift is not functioning.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Not implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Buy this car - it has power steering. Assumption: People prefer power steering.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: School will remain closed tomorrow. Assumption: Students can read the notice.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Warning: Smoking is injurious to health. Assumption: People can read.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Interview on Sunday at 10 AM. Assumption: Candidate will be available on Sunday.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Study hard to get good marks. Assumption: Studying leads to good marks.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Join our gym to lose weight. Assumption: People want to lose weight.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Keep your valuables in locker. Assumption: Lockers are safe.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Statement & Assumption', 'Statement: Bring your ID proof. Assumption: Everyone has ID proof.', 'Implicit', 'Not implicit', 'Cannot determine', 'Partially implicit', 'Implicit'),
('Reasoning', 'Cause & Effect', 'Event I: Heavy rainfall. Event II: Flood in city. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'I is cause, II is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Company announced bonus. Event II: Employees are happy. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'I is cause, II is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Roads are wet. Event II: It rained last night. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'II is cause, I is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Price of petrol increased. Event II: People using public transport more. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'I is cause, II is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Government banned plastic bags. Event II: Use of cloth bags increased. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'I is cause, II is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Student studied hard. Event II: Student got good marks. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'I is cause, II is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Power cut in area. Event II: Transformer failure. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'II is cause, I is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Traffic jam on highway. Event II: Accident occurred. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'II is cause, I is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Temperature dropped suddenly. Event II: People wearing warm clothes. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'I is cause, II is effect'),
('Reasoning', 'Cause & Effect', 'Event I: Sale announced in mall. Event II: Large crowd in mall. What is relation?', 'I is cause, II is effect', 'II is cause, I is effect', 'Both independent', 'Both effects of common cause', 'I is cause, II is effect'),
('Reasoning', 'Puzzle Test', 'Five friends P, Q, R, S, T are sitting in a row. P and Q are neighbors. T is not at ends. S is left of Q. Who is in middle?', 'P', 'Q', 'R', 'T', 'Q'),
('Reasoning', 'Puzzle Test', 'A, B, C, D, E are five students. A is taller than B but shorter than C. D is tallest. E is shorter than B. Who is shortest?', 'A', 'B', 'C', 'E', 'E'),
('Reasoning', 'Puzzle Test', 'Five persons A, B, C, D, E are sitting in circle facing center. A is 2nd left of E. C is between E and D. Who is immediate right of A?', 'B', 'C', 'D', 'E', 'B'),
('Reasoning', 'Puzzle Test', 'P, Q, R, S, T are of different ages. P is older than Q. R is younger than S but older than T. S is younger than Q. Who is youngest?', 'P', 'Q', 'R', 'T', 'T'),
('Reasoning', 'Puzzle Test', 'Four friends A, B, C, D live on different floors. A lives above B. C lives below D. B lives above D. Who lives on top floor?', 'A', 'B', 'C', 'D', 'A'),
('Reasoning', 'Puzzle Test', 'Five books P, Q, R, S, T are kept one above other. R is above S but below P. Q is above T but below S. Which book is at bottom?', 'P', 'Q', 'S', 'T', 'T'),
('Reasoning', 'Puzzle Test', 'A, B, C, D, E are sitting in row facing north. C is left of D. B is right of E. A is between E and C. Who is at extreme right?', 'A', 'B', 'C', 'D', 'D'),
('Reasoning', 'Puzzle Test', 'Five cities P, Q, R, S, T are at different distances from city X. P is farther than Q. R is nearer than S. T is farther than P. Which is nearest?', 'P', 'Q', 'R', 'S', 'R'),
('Reasoning', 'Puzzle Test', 'P, Q, R, S are four friends. P is richer than Q. S is poorer than R but richer than Q. Who is poorest?', 'P', 'Q', 'R', 'S', 'Q'),
('Reasoning', 'Puzzle Test', 'Five persons are standing in queue. A is between B and C. D is ahead of E. B is ahead of D. Who is last in queue?', 'A', 'C', 'D', 'E', 'E'),,
